# Juliaにおけるベクトル・行列のあれこれ

## 行列の作成

In [6]:
#これはベクトル
[1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [7]:
#これは1×4行列
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [8]:
#型は統一
[1, 2, 3.0, 4, 5]

5-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [4]:
#これは2-element Array(ベクトル)
[[1,2,3],[4,5,6]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [5]:
#コンマを無くすとそれぞれが列ベクトルになり、行列を作る
[[1,2,3] [4,5,6]]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [9]:
#初期化されていないベクトル
#undefを入れると適当な値が入る
array = Array{Int64}(undef, 5)

5-element Array{Int64,1}:
 4598099280
 4598099312
 4598099440
 4550495088
 4550492736

In [11]:
#行列でもできるけどちょっとおかしい。。。
matrix = Array{Int64}(undef, 5, 2)

5×2 Array{Int64,2}:
 4595518848  4595519088
 4595518768           3
          1           3
 4595518928           2
 4595519008  4591585025

In [12]:
#ランダムな値によるベクトル作成
rand(5)

5-element Array{Float64,1}:
 0.3418234037989183 
 0.8749697873425668 
 0.9306205166957364 
 0.07062597718054953
 0.14041144433516317

In [13]:
#行列も同じ
rand(5,2)

5×2 Array{Float64,2}:
 0.798014  0.443808
 0.359307  0.75305 
 0.556226  0.263601
 0.655363  0.920269
 0.763124  0.142383

In [14]:
#行列のサイズを返す
matrix = ones(5,5)
size(matrix)

(5, 5)

In [20]:
#３次元行列
multidim = ones(2,2,2)

2×2×2 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0
 1.0  1.0

[:, :, 2] =
 1.0  1.0
 1.0  1.0

In [22]:
#サイズも同じように返せる
size(multidim)

(2, 2, 2)

In [29]:
#要素が全部同じの行列
fill(42, 9)

9-element Array{Int64,1}:
 42
 42
 42
 42
 42
 42
 42
 42
 42

In [30]:
#こんなのもできる
fill("hi", 4,2)

4×2 Array{String,2}:
 "hi"  "hi"
 "hi"  "hi"
 "hi"  "hi"
 "hi"  "hi"

### repeat

In [33]:
#要素の繰り返し
repeat([1,2,3],2)

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

In [34]:
#行列化
repeat([1,2,3],2,3)

6×3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3

In [35]:
#inner = [2, 3] makes an array with two copies of each row and three copies of each column:
repeat([1, 2], inner = [2, 3])

4×3 Array{Int64,2}:
 1  1  1
 1  1  1
 2  2  2
 2  2  2

In [36]:
#outer = [2,3]
repeat([1, 2], outer = [2, 3])

4×3 Array{Int64,2}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2

## 行列の扱い

### 転置とか

In [38]:
M = reshape(1:12, 3, 4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [39]:
#転置その１
transpose(M)

4×3 LinearAlgebra.Transpose{Int64,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [40]:
#転置その２
M'

4×3 LinearAlgebra.Adjoint{Int64,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

### 逆行列、行列式、ランク、トレース

In [41]:
using Pkg
Pkg.add("LinearAlgebra")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %13.5 %>                             ]  27.0 %Fetching: [================>                        ]  37.9 %                   ]  51.3 %Fetching: [======================>                  ]  54.8 %>            ]  68.2 % [=================================>       ]  81.7 % ]  95.1 % Resolving package versions...
 Installed PDMats ─ v0.9.6
 Installed DSP ──── v0.5.2
  Updating `~/.julia/environments/v1.0/Project.toml`
  [37e2e46d] + LinearAlgebra 
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [717857b8] ↑ DSP v0.5.1 ⇒ v0.5.2
  [90014a1f] ↑ PDMats v0.9.5 ⇒ v0.9.6


In [42]:
#LinearAlgebraパッケージを使う
using LinearAlgebra

In [43]:
#randはランダムな値で行列を作る
A = rand(2:8, 3, 3)

3×3 Array{Int64,2}:
 6  5  5
 7  5  8
 5  4  2

In [44]:
#行列式
det(A)

12.999999999999975

In [45]:
#逆行列
inv(A)

3×3 Array{Float64,2}:
 -1.69231    0.769231    1.15385 
  2.0       -1.0        -1.0     
  0.230769   0.0769231  -0.384615

In [46]:
#行列のランク
rank(A)

3

In [47]:
#トレース
tr(A)

13

### 行列の削除

In [1]:
a = [1.0, 1.1, 1.2, 1.3]
b = [2.2, 2.4, 2.6, 2.8]
c = [3.9, 3.6, 3.3, 3.1]

m = hcat(a,b,c)

4×3 Array{Float64,2}:
 1.0  2.2  3.9
 1.1  2.4  3.6
 1.2  2.6  3.3
 1.3  2.8  3.1

In [2]:
#２行目を削除
m[1:size(m,1) .!= 2,: ]

3×3 Array{Float64,2}:
 1.0  2.2  3.9
 1.2  2.6  3.3
 1.3  2.8  3.1

In [25]:
#setdiffを使ったやり方
m[setdiff(1:end, 2), :]

3×3 Array{Float64,2}:
 1.0  2.2  3.9
 1.2  2.6  3.3
 1.3  2.8  3.1

In [3]:
#２列目を削除
m[:, 1:size(m)[2] .!= 2]

4×2 Array{Float64,2}:
 1.0  3.9
 1.1  3.6
 1.2  3.3
 1.3  3.1

In [26]:
#3次元以上のとき
A = ones(3,3,3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [28]:
#indexを手動で作ってあげれば特定の行・列だけ抜き出せる
ind = [1:3, 1:3, 1:2]
A[ind...]　#A[ind...] は A[1:3, 1:3, 1:2]を表す（...の意味）

3×3×2 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

### copy

In [37]:
a = collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

## いろんな計算

In [15]:
#要素の積を返す
prod([1,2,4])

8

In [18]:
#dimensionの指定
A = [1 2 3 4; 5 6 7 8]
println(prod(A, dims=1)) #列の積
println(prod(A, dims=2)) #行の積

[5 12 21 32]
[24; 1680]


In [10]:
#要素ごとの計算
X = [1 2 3 4; 5 6 7 8]
Y = [1; 2]
X .- Y

2×4 Array{Int64,2}:
 0  1  2  3
 3  4  5  6

In [11]:
#これはダメ
X = [1 2 3 4; 5 6 7 8]
Y = [1; 2]
X - Y

DimensionMismatch: DimensionMismatch("dimensions must match")

## 距離

In [48]:
#LinearAlgebraパッケージを使う
using LinearAlgebra

In [49]:
#使用するベクトル
X = [-2, 4, 1]

3-element Array{Int64,1}:
 -2
  4
  1

In [50]:
#Euclidean Norm
norm(X)

4.58257569495584

In [51]:
#1-norm
norm(X, 1)

7.0

In [53]:
#inf-norm
norm(X, Inf)

4.0

## 平均とか

In [5]:
using Distributions

In [6]:
a = [1 2 3 4; 5 6 7 8]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [7]:
#各列の平均
mean(a, dims=1)

1×4 Array{Float64,2}:
 3.0  4.0  5.0  6.0

In [8]:
#各行の平均
mean(a, dims=2)

2×1 Array{Float64,2}:
 2.5
 6.5