## Hello World

In [1]:
#Pythonではprint関数だったが、Juliaではprintln関数
#printは改行しない
println("Hello World")

Hello World


In [2]:
hello_world = "Hello World"
typeof(hello_world)

String

In [3]:
println(hello_world)

Hello World


## Basic Math

In [4]:
a = 10+7

17

In [5]:
b = 10-7

3

In [6]:
c = 10*7

70

In [7]:
d = 10/7

1.4285714285714286

In [8]:
#Pythonとの違い
e = 10^7

10000000

In [9]:
f = 10%7

3

## String

In [10]:
str1 = "string"

"string"

In [11]:
str2 = """これもstring"""

"これもstring"

In [12]:
println("""ダブルクオーテーションをつかうときは"こう"する""")

ダブルクオーテーションをつかうときは"こう"する


In [13]:
# Pythonだと''でくくった文字列は、stringとして扱われるが、Juliaだとcharacter型として扱われる。
typeof('a')

Char

In [14]:
#シングルクオーテーションはダメ
#要はJuliaの場合、シングルクオーテーションはcharacter型、ダブルクオーテーションはstring型になる
char1 = 'これはエラー'

LoadError: syntax: invalid character literal

## 変数を文字列として扱う

In [15]:
# 変数の先頭に $ を入れることで、変数の中の値を出力できる。
# Pythonよりもシンプルに書ける。
num = 10
println("この値は$num です")

この値は10 です


In [16]:
# こんなこともできるらしい。
println("$num ＋ $num = $(num + num)")

10 ＋ 10 = 20


## 文字列の結合

In [17]:
# string()のカッコの中に、カンマ区切りで入れていくことで、実現可能らしい。
string("私", "は", "犬です")

"私は犬です"

In [18]:
# 変数も同じ感じで処理してくれる
string("この値は", num, "です")

"この値は10です"

In [19]:
# int型なども同様
string("この値は", 10, "です")

"この値は10です"

In [20]:
# ただ、Pythonでは出来る、以下のような文字の連結はできないらしい。
"これは" + "できません"

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502

In [21]:
# Pythonだと、文字列が何回も繰り返しで出力される表現で、文字列の連結ができるっぽい。
"これは" * "できる"

"これはできる"

## character型の結合

In [22]:
# character型の文字を結合させて、文字列にすることも可能っぽい。
char1 = 'a'
char2 = 'b'
string(char1, char2)

"ab"

## Tuple

In [23]:
# 普通のTupleの定義の仕方はPythonと同じ
tuple_data = ("apple", "orange", "banana")
several_types = (1, "apple", 2)
tuple_2d = ((1,2,3), (2,3,4))

((1, 2, 3), (2, 3, 4))

In [24]:
# 要素の取り出し方は異なる、先頭は０ではなく１
tuple_data[1]

"apple"

In [25]:
# これはPythonとは少し違う挙動。リストが一要素として入る
tuple([1,2,3])

([1, 2, 3],)

In [26]:
# これはPythonではエラーが出るが、Juliaだとこれでtupleを定義できるらしい
tuple(1,2,3)

(1, 2, 3)

In [27]:
# もちろん、tupleは不変なので、情報の更新などはできない。
tuple_data[1] = "peach"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

## Arrays

In [1]:
# まずは普通に配列を定義。
# この指定の仕方はPythonとも同じ。
fruits = ["Apple", "Orange", "Banana"]

3-element Array{String,1}:
 "Apple" 
 "Orange"
 "Banana"

In [2]:
# 要素の取得
# indexはPythonとは違って1始まりなので、注意。
fruits[1]

"Apple"

In [3]:
# 0を指定するとエラーになる
fruits[0]

BoundsError: BoundsError: attempt to access 3-element Array{String,1} at index [0]

In [4]:
# pushとpopもできる
#pushは配列の最後に要素を追加
#popは配列の最後の要素を削除
push!(fruits, "Peach")
println(fruits)
pop!(fruits)
println(fruits)

["Apple", "Orange", "Banana", "Peach"]
["Apple", "Orange", "Banana"]


In [5]:
# 要素にアクセスして情報も更新できる
fruits[1] = "Apple2"
fruits

3-element Array{String,1}:
 "Apple2"
 "Orange"
 "Banana"

## 多次元配列

In [6]:
# もちろん、これも普通にできる
fruits_2d = [["Apple", "Orange", "Banana"], ["Apple", "Orange", "Banana", "Peach"]]

2-element Array{Array{String,1},1}:
 ["Apple", "Orange", "Banana"]         
 ["Apple", "Orange", "Banana", "Peach"]

In [7]:
# 乱数発生。モジュールのインポートは不要
rand(4,3)

4×3 Array{Float64,2}:
 0.983463  0.444555  0.988348
 0.861458  0.228344  0.213957
 0.449313  0.427337  0.683473
 0.548947  0.474501  0.780371

In [61]:
#one dimentional array
a = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [62]:
#two dimentional array (1 x n)
a = [1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

## 配列の初期化

In [27]:
# numpyとかで配列を初期化するときによく使うzeros
# 普通の1d-array
println(zeros(5))

# 多次元配列も可能
println(zeros(2,4))

# 型の指定もできる
println(zeros(Int8, 2,4))

# 型の変換
# 出力が、「0 => 0.0」 となっているのに注目
#Julia1.0.1ではできない???
zeros_array = zeros(Int8, 2,4)
println(zeros(zeros_array, Float64))

[0.0, 0.0, 0.0, 0.0, 0.0]
[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]
Int8[0 0 0 0; 0 0 0 0]


MethodError: MethodError: no method matching zeros(::Type{Float64}, ::Array{Int8,2})
Closest candidates are:
  zeros(::Type{T}, !Matched::Union{Integer, AbstractUnitRange}...) where T at array.jl:464
  zeros(::Type{T}, !Matched::Tuple{}) where T at array.jl:468
  zeros(::Type{T}, !Matched::Tuple{Vararg{Integer,N}}) where {T, N} at array.jl:467
  ...

In [9]:
# onesもある。似たような感じで使える。
# 普通の1d-array
println(ones(5))

# 多次元配列も可能
println(ones(2,4))

# 型の指定もできる
println(ones(Int8, 2,4))

# 型の変換もできる
#Julia1.0.1ではできない???
ones_array = ones(Int8, 2,4)
println(ones(ones_array, Float64))

[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
Int8[1 1 1 1; 1 1 1 1]


MethodError: MethodError: no method matching ones(::Array{Int8,2}, ::Type{Float64})

In [10]:
# 0や1, trueやfalse以外の値を入れたい場合は、fill関数を使うと良いっぽい。
fill(10, (3,2))

3×2 Array{Int64,2}:
 10  10
 10  10
 10  10

## 配列の情報取得

In [11]:
#Example
ones_2d = ones(2,3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [12]:
# 配列のdimentionを取得
ndims(ones_2d)

2

In [13]:
#indexを取得する関数
#Julia1.0.1ではindices関数は無い???
indices(ones_2d)

UndefVarError: UndefVarError: indices not defined

In [14]:
# 「長さ」ではなくて、「要素の数」を取得する関数であることに注意。
# Pythonのlenとは違う
length(ones_2d)

6

In [15]:
# 要素へのインデックスをiterableな形で取得
eachindex(ones_2d)

Base.OneTo(6)

In [16]:
# 呼び出しの例。以下は、for文の例。
for iter in eachindex(ones_2d)
    println(iter, "=>", ones_2d[iter])
end

1=>1.0
2=>1.0
3=>1.0
4=>1.0
5=>1.0
6=>1.0


In [17]:
# non-zeroな要素の数を返してくれる関数
# Julia1.0.1ではcountnz関数は無い???
countnz(ones_2d)

UndefVarError: UndefVarError: countnz not defined

## 配列の操作

In [18]:
# reshape
# Pythonと同じ
ones_1d = ones(16)
reshape(ones_1d, (4,4))

4×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [19]:
# 片方の次元だけ指定するパターンも可能
reshape(ones_1d, 2, :)

2×8 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [20]:
# reshape不可能な数を渡したらエラー
reshape(ones_1d, 3, :)

DimensionMismatch: DimensionMismatch("array size 16 must be divisible by the product of the new dimensions (3, Colon())")

In [21]:
# verticalな方向に結合する
a = [1 2 3 4 5]
b = [6 7 8 9 10; 11 12 13 14 15]
vcat(a, b)

3×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [22]:
# Horizontalな方向に結合する
a = [1; 2; 3; 4; 5;]
b = [6; 7; 8; 9; 10;]
hcat(a, b)

5×2 Array{Int64,2}:
 1   6
 2   7
 3   8
 4   9
 5  10

## 配列の演算

In [1]:
#各要素に四則演算
#+と-の前にドットをつける？？？
a = [1, 2, 3, 4, 5]
println(a .+ 1)
println(a .- 1)
println(a * 2)
println(a / 2)

[2, 3, 4, 5, 6]
[0, 1, 2, 3, 4]
[2, 4, 6, 8, 10]
[0.5, 1.0, 1.5, 2.0, 2.5]


In [24]:
# 累積演算
accumulate(+, [1,2,3])

3-element Array{Int64,1}:
 1
 3
 6

In [26]:
# 最後にinitを指定するとそこから計算する。
# 以下の例であれば、100+1が最初に出てくる。
accumulate(+,  [1,2,3], init=100)

3-element Array{Int64,1}:
 101
 103
 106

In [28]:
#四則演算だけでなく他のminとかでも大丈夫
accumulate(min, [1,2,-1], init=0)

3-element Array{Int64,1}:
  0
  0
 -1

## 辞書型

In [29]:
# 定義の仕方
# Pythonは「:」だが、Juliaでは「=>」になる。
fruits = Dict("Apple" => 1, "Banana" => 2, "Orange" => 3)

Dict{String,Int64} with 3 entries:
  "Apple"  => 1
  "Orange" => 3
  "Banana" => 2

In [30]:
# 要素へのアクセス方法はキーを指定するだけ
fruits["Apple"]

1

In [31]:
# 要素の追加
fruits["Peach"] = 4
println(fruits)

# 更新
fruits["Peach"] = 3
println(fruits["Peach"])

# 削除
pop!(fruits, "Peach")
println(fruits)

# popでもできるが、delete!を使う方が直感的
fruits["Peach"] = 3
delete!(fruits, "Peach")

Dict("Apple"=>1,"Orange"=>3,"Peach"=>4,"Banana"=>2)
3
Dict("Apple"=>1,"Orange"=>3,"Banana"=>2)


Dict{String,Int64} with 3 entries:
  "Apple"  => 1
  "Orange" => 3
  "Banana" => 2

In [32]:
# 辞書型は順序という概念を持っていないので、indexでアクセスはできない
fruits[1]

KeyError: KeyError: key 1 not found

## 辞書型の操作

In [33]:
# キーを持っているかどうかの判定
haskey(fruits, "Apple") # true

true

In [34]:
# get(dict, key, default)で、値を取得できる。defaultは、keyがdictになかったときに返ってくる値

# Appleがkeyにあるので、そのvalueを返す
println(get(fruits, "Apple", 100))

# Peachがkeyにないので、100を返す
println(get(fruits, "Peach", 100))

1
100


In [35]:
# pop
# Pythonと同じ
fruits["Peach"] = 3
println(pop!(fruits, "Peach")) # Peachの値が返ってくる
println(fruits) # Peachのkeyとvalueはなくなっている

3
Dict("Apple"=>1,"Orange"=>3,"Banana"=>2)


In [36]:
# keyの一覧を取得
keys(fruits)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "Apple"
  "Orange"
  "Banana"

In [37]:
# valueの一覧を取得
values(fruits)

Base.ValueIterator for a Dict{String,Int64} with 3 entries. Values:
  1
  3
  2

In [38]:
# 複数の辞書のマージも可能
a = Dict("Apple" => 1, "Banana" => 2)
b = Dict("Banana" => 3, "Peach" => 4)

# 以下の二つのBananaの値の違いに注目
# ２つ目の引数の方が優先される
println(merge(a, b))
println(merge(b, a))

Dict("Apple"=>1,"Peach"=>4,"Banana"=>3)
Dict("Apple"=>1,"Peach"=>4,"Banana"=>2)


## Sets

In [39]:
# 定義の仕方
# Pythonと違い大文字
fruits = Set(["apple", "banana", "orange"])

Set(["orange", "banana", "apple"])

In [40]:
# 型の自動判定もしてくれるが、自分で指定もできる。
fruits = Set{String}(["apple", "banana", "orange"])

Set(["orange", "banana", "apple"])

In [41]:
# 複数の型の値も入れられる
fruits = Set(["apple", "banana", "orange", 1])

Set(Any["orange", "banana", "apple", 1])

In [42]:
# 空集合の定義
fruits = Set()

Set(Any[])

In [44]:
# 型を指定しておくこともできる。
fruits = Set{String}()

Set(String[])

## 集合に要素を追加

In [45]:
# 要素の追加。pushを使う
fruits = Set()
push!(fruits, "apple")
fruits

Set(Any["apple"])

In [46]:
# 同じ要素を追加しても、集合なので一つだけしか保持しない。エラーも出ない
fruits = Set()
push!(fruits, "apple")
push!(fruits, "apple")
fruits

Set(Any["apple"])

In [48]:
# 型を指定しておいたものに、その型で扱えない値を入れようとすると当然エラーになる
fruits = Set{String}()
push!(fruits, 1)
fruits

MethodError: MethodError: Cannot `convert` an object of type Int64 to an object of type String
Closest candidates are:
  convert(::Type{T<:AbstractString}, !Matched::T<:AbstractString) where T<:AbstractString at strings/basic.jl:207
  convert(::Type{T<:AbstractString}, !Matched::AbstractString) where T<:AbstractString at strings/basic.jl:208
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154

## 集合の要素の削除

In [49]:
# 要素の削除は、popを使う
fruits = Set(["apple", "banana"])
pop!(fruits, "apple")
fruits

Set(["banana"])

In [50]:
# 存在しない要素を削除しようとすると、エラーがでる。
fruits = Set(["apple", "banana"])
pop!(fruits, "orange")
fruits

KeyError: KeyError: key "orange" not found

## 集合の要素の存在判定

In [51]:
# 要素が存在しているかどうかを判定
fruits = Set(["apple", "banana"])
in("banana", fruits) # true

true

## 集合同士の演算

In [52]:
# ここで使う集合をまず定義
fruits = Set(["apple", "banana", "orange"])
another_fruits = Set(["apple", "peach"])
drink = Set(["coffee", "yogurt drink", "cocoa"])
number = Set([1,2,3,4])

Set([4, 2, 3, 1])

## 和集合

In [53]:
# 同じ型の集合の和集合
union(fruits, drink)

Set(["orange", "coffee", "yogurt drink", "banana", "cocoa", "apple"])

In [54]:
# 違う型の集合の和集合をとると、型が変わる。
union(fruits, number)

Set(Any[4, 2, "orange", 3, "banana", "apple", 1])

## 積集合

In [55]:
# 積集合
intersect(fruits, another_fruits)

Set(["apple"])

In [56]:
# 積集合が空集合
intersect(fruits, drink)

Set(String[])

## 差集合

In [57]:
# 差集合
setdiff(fruits, another_fruits)

Set(["orange", "banana"])

## while

In [63]:
#Pythonではコロンが必要だったがJuliaでは必要ない
i = 0
while i < 10
    i += 1
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [64]:
#Example2
fruits = ["apple", "banana", "orange"]
i = 1
while i <= length(fruits)
    println(fruits[i])
    i += 1
end

apple
banana
orange


## for

In [65]:
# for loopはPythonに似たような感じの使い方ができる。
# コロンは必要ない
for i = 1:5
    println(i)
end

1
2
3
4
5


In [66]:
# iterableであればいいので、配列のループも可能
fruits = ["apple", "banana", "orange"]
for i in fruits
    println(i)
end

apple
banana
orange


In [67]:
# タプルも可能
fruits = ("apple", "banana", "orange")
for i in fruits
    println(i)
end

apple
banana
orange


In [68]:
# 辞書も可能
fruits = Dict("apple" => 1, "banana" => 2, "orange" => 3)

# 変数の部分にカッコをつけないとエラー
for (k, v) in fruits
    println("$k は $v 個あります")
end

orange は 3 個あります
banana は 2 個あります
apple は 1 個あります


In [69]:
# 文字列のループも可能
#Pythonと同じ
apple = "apple"
for i in apple
    println(i)
end

a
p
p
l
e


## 特殊なループ

In [70]:
# 2つ以上の配列のループ
# Pythonだと2重ループにする必要があるが、一行で済む。
for i = 1:2, j = 2:3
    println((i, j))
end

(1, 2)
(1, 3)
(2, 2)
(2, 3)


In [71]:
# それぞれの配列の要素の数が異なっていても良い
for i = 1:2, j = 2:5
    println((i, j))
end

(1, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 2)
(2, 3)
(2, 4)
(2, 5)


In [72]:
# 同時にループを回したい場合は、zip関数を使う
# Pythonと同じ
for (i, j) in zip(1:2, 3:4)
    println((i, j))
end

(1, 3)
(2, 4)


## 内包表記

In [73]:
#Example1
fruits = [i for i in ["apple", "banana", "orange"]]
println(fruits)

["apple", "banana", "orange"]


In [74]:
# 2重の内包表記
fruits_num = [i + j for i in 1:100, j in 101:200]

100×100 Array{Int64,2}:
 102  103  104  105  106  107  108  109  …  195  196  197  198  199  200  201
 103  104  105  106  107  108  109  110     196  197  198  199  200  201  202
 104  105  106  107  108  109  110  111     197  198  199  200  201  202  203
 105  106  107  108  109  110  111  112     198  199  200  201  202  203  204
 106  107  108  109  110  111  112  113     199  200  201  202  203  204  205
 107  108  109  110  111  112  113  114  …  200  201  202  203  204  205  206
 108  109  110  111  112  113  114  115     201  202  203  204  205  206  207
 109  110  111  112  113  114  115  116     202  203  204  205  206  207  208
 110  111  112  113  114  115  116  117     203  204  205  206  207  208  209
 111  112  113  114  115  116  117  118     204  205  206  207  208  209  210
 112  113  114  115  116  117  118  119  …  205  206  207  208  209  210  211
 113  114  115  116  117  118  119  120     206  207  208  209  210  211  212
 114  115  116  117  118  119  120  121 

## Compound Expression

In [2]:
#複数の式の計算を１つにまとめる
fruits = begin
    apple = "apple"
    orange = "orange"
    [apple, orange]
end

2-element Array{String,1}:
 "apple" 
 "orange"

In [3]:
# 「;」でもOK
z = (apple = "apple"; orange = "orange"; [apple, orange])

2-element Array{String,1}:
 "apple" 
 "orange"

## if

In [4]:
# if文の書き方はPythonと同じ、elseifだけ違う
# Pythonと異なりコロンがいらない
function if_example(x, y)
    if x < y
        println("x : $x は y : $y よりも小さい")
    elseif x > y
        println("x : $x は y : $y よりも大きい")
    else
        println("x : $x と y : $y は等しい")
    end
end

if_example (generic function with 1 method)

In [5]:
if_example(100, 1)

x : 100 は y : 1 よりも大きい


In [6]:
# このような書き方もOK
N = 15
if (N % 3 == 0) & (N % 5 == 0)
    println("FizzBuzz")
end

FizzBuzz


## 三項演算子

a ? b : cは

if a, b else c  end

を表す

In [7]:
# Example
x = (10 > 5) ? 10 : 5

10

In [8]:
# 出力を返すときにも使える
println(10 < 5 ? "true" : "false")

false


In [9]:
# 三項演算子でif-elseif-elseみたいなこともできる
example(x, y) = println(x < y ? "$x は $y よりも小さい(if)" :
                        x > y ? "$x は $y よりも大きい(elseif)" : "$x と $y は等しい")

example (generic function with 1 method)

In [10]:
example(100,1)

100 は 1 よりも大きい(elseif)


In [11]:
example(2,5)

2 は 5 よりも小さい(if)


In [12]:
example(3,3)

3 と 3 は等しい


## &と&&の違い

In [13]:
# この２つはどちらも、「２つの条件がともに真の時、trueを返す」が、挙動が違う
# 以下は、果物の個数を出力した後にtrueとfalseをそれぞれ返す関数
apple_true(x) = (println("apple => $x"); true)
orange_false(x) = (println("orange => $x"); false)

apple_true(1) & orange_false(2)

apple => 1
orange => 2


false

In [14]:
# &では、一つ目の要素がtrueでもfalseでも両方評価
# そのため、一つ目がfalseを返しても、二つ目も評価する
orange_false(2) & apple_true(1)

orange => 2
apple => 1


false

In [15]:
# これは&と同じ挙動
apple_true(1) && orange_false(2)

apple => 1
orange => 2


false

In [16]:
# &&では、一つ目の要素を評価してfalseであればそこで評価を止める
# 以下のコードでは、二つ目の評価を行わない
orange_false(2) && apple_true(1)

orange => 2


false

## |と||の違い

In [17]:
# この２つはどちらも、「２つの条件のどちらかが真の時、trueを返すが、挙動が違う

# 以下は、一つ目がtrueの場合、2つ目を評価する必要がないのに、評価しています。
apple_true(1) | orange_false(2)

apple => 1
orange => 2


true

In [18]:
# これが「||」の場合だと、二つ目を評価しない
apple_true(1) || orange_false(2)

apple => 1


true

## 関数の定義

In [19]:
# Juliaではfunction～endで関数を定義する
function say_name(name)
    println("$name")
end

say_name (generic function with 1 method)

In [20]:
say_name("banana")

banana


## 代入形式での関数の定義

In [21]:
# ワンライナーで関数宣言も可能
say_name_oneline(name) = println("$name")

say_name_oneline (generic function with 1 method)

In [22]:
say_name_oneline("banana")

banana


In [23]:
# 複数行でもOK
say_name_lines(name) = begin
    output = name 
    println(output)
end

say_name_lines (generic function with 1 method)

In [24]:
say_name_lines("orange")

orange


## 無名関数

In [25]:
# pythonでのlambdaみたいな
say_name_anonymous = name -> println("$name")

#3 (generic function with 1 method)

In [26]:
say_name_anonymous("banana")

banana


## return

In [27]:
# juliaではdefaultで、一番最後に評価した値を返す
# return文を使わなくても値を返す

function sample(x, y)
    x + y
end

# return使わないけど値は返ってくる
value = sample(5, 10)
println(value)

15


In [28]:
# returnを使うとそこで強制的に値を返す
function sample_return(x, y)
    return x * y
    x + y
end

value = sample_return(5, 10)
println(value)

50


In [29]:
# returnで値を返すとそれ以降の処理をしない
function fizzbuzz(x)
    if x % 3 == 0 && x % 5 == 0
        return "fizzbuzz"
    elseif x % 3 == 0
        return "fizz"
    elseif x % 5 == 0
        return "buzz"
    else
        return ""
    end
end

fizzbuzz (generic function with 1 method)

In [30]:
fizzbuzz(15)

"fizzbuzz"

## operatorを利用した関数

In [31]:
# こんなことできる
+(1, 2, 3)

6

In [32]:
# juliaでは、ほとんどのoperatorが関数として特別なsytaxをサポートしている
*(1, 2, 3, 4)

24

In [33]:
# これもOK
f = +
f(1,2,3)

6

# 型システム

## 型構造

In [2]:
#Intは具体型
isconcretetype(Int64)

true

In [4]:
#Integerは抽象型
isconcretetype(Integer)

false

In [5]:
#Int型はInteger型のsubtype
#subtype/supertypeの関係は<:を使って確認
Int64 <: Integer

true

In [6]:
#Bool型もInteger型のsubtype
Bool <: Integer

true

In [7]:
#subtype/supertypeの関係を返す関数
function tracetype(t)
    print(t)
    while t != supertype(t)
        print(" <: ")
        t = supertype(t)
        print(t)
    end
    println()
end

tracetype (generic function with 1 method)

In [8]:
#Int64から上に遡る
tracetype(Int64)

Int64 <: Signed <: Integer <: Real <: Number <: Any


In [9]:
#Boolから上に遡る
tracetype(Bool)

Bool <: Integer <: Real <: Number <: Any


In [10]:
#Float64から上に遡る
tracetype(Float64)

Float64 <: AbstractFloat <: Real <: Number <: Any


## 型パラメータ

In [11]:
#[1,2,3]はInt64型を要素とする一次元配列であることを示す
typeof([1,2,3])

Array{Int64,1}

In [12]:
#これは行列になるので二次元配列
typeof([1 2 3])

Array{Int64,2}

In [13]:
#これも行列
typeof([1 2 3; 4 5 6])

Array{Int64,2}

## 型定義

In [14]:
#型を自分で作ることができる
#Pythonのclassみたいな
#"mutable struct"もしくは"struct"から始める
mutable struct Person
    name::String
    age::Int
end

struct Location
    x::Float64
    y::Float64
end

In [15]:
person = Person("Alice", 24)

Person("Alice", 24)

In [16]:
location = Location(2.3, 4.5)

Location(2.3, 4.5)

In [17]:
#更新もできる
person.age += 1

25

In [18]:
person

Person("Alice", 25)

In [19]:
location.x, location.y

(2.3, 4.5)

In [20]:
#structで作られた型のフィールド値は更新できない（イミュータブルなので）
location += 1.2

MethodError: MethodError: no method matching +(::Location, ::Float64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  +(!Matched::Bool, ::T<:AbstractFloat) where T<:AbstractFloat at bool.jl:112
  +(!Matched::Float64, ::Float64) at float.jl:395
  ...

## 多重ディスパッチ

In [21]:
#<引数>::<型>のように引数の型を指定することができる
function add(x::Int, y::Int)
    return x + y
end

add (generic function with 1 method)

In [22]:
add(2,3)

5

In [23]:
#型が合わないとエラー
add(2.0,3.0)

MethodError: MethodError: no method matching add(::Float64, ::Float64)

In [24]:
#同じ名前の関数を作る
function add(x::Float64, y::Float64)
    return x + y
end

add (generic function with 2 methods)

In [25]:
add(2.0,3.0)

5.0

In [26]:
#先に定義した関数も使えるまま
#関数の上書きにならない
add(2,3)

5

引数の型に合わせて呼び出すメソッドが変わる　-> **多重ディスパッチ**

## コンストラクタ

In [27]:
#Red-Green-Blueの３原色を指定して符号なし8ビット整数でエンコーディング
struct RGB
    r::UInt8
    g::UInt8
    b::UInt8

    #内部コンストラクタ
    #与えられた値が8bitで表現できるかチェック
    function RGB(r, g, b)
        @assert 0 <= r <= 255
        @assert 0 <= g <= 255
        @assert 0 <= b <= 255
        return new(r, g, b)
    end
end

In [28]:
RGB(1,2,3)

RGB(0x01, 0x02, 0x03)

In [29]:
#300は8bitで表現できないのでエラー
RGB(1,300,3)

AssertionError: AssertionError: 0 <= g <= 255

In [30]:
#外部コンストラクタから簡便なコンストラクタを定義
RGB(x) = RGB(x,x,x)

RGB

In [31]:
#上のコンストラクタから新たなコンストラクタを定義
RGB() = RGB(0)

RGB

In [32]:
#多重ディスパッチのおかげで全部OK
RGB(), RGB(1),RGB(2,3,4)

(RGB(0x00, 0x00, 0x00), RGB(0x01, 0x01, 0x01), RGB(0x02, 0x03, 0x04))

# メタプログラミング

## @show

In [33]:
x = 3.14

3.14

In [34]:
#@showは変数の値を確認してくれる
@show x

x = 3.14


3.14

In [35]:
insertionsort(xs) = insertionsort!(copy(xs))

function insertionsort!(xs)
    @show xs
    for i in 2:length(xs)
        j = i
        while j > 1 && xs[j-1] > xs[j]
            xs[j-1], xs[j] = xs[j], xs[j-1]
            j -= 1
        end
        @show xs
    end
    xs
end

insertionsort! (generic function with 1 method)

In [36]:
#ソートの様子を確認できる
insertionsort([6,5,3,1,8,7,2,4])

xs = [6, 5, 3, 1, 8, 7, 2, 4]
xs = [5, 6, 3, 1, 8, 7, 2, 4]
xs = [3, 5, 6, 1, 8, 7, 2, 4]
xs = [1, 3, 5, 6, 8, 7, 2, 4]
xs = [1, 3, 5, 6, 8, 7, 2, 4]
xs = [1, 3, 5, 6, 7, 8, 2, 4]
xs = [1, 2, 3, 5, 6, 7, 8, 4]
xs = [1, 2, 3, 4, 5, 6, 7, 8]


8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

## @assert

In [37]:
x = 1

1

In [38]:
#@assertは条件の真偽を確かめてくれる
#Trueなら何も返さない
@assert x == 1

In [39]:
#Falseならエラーを返す
@assert x == 2

AssertionError: AssertionError: x == 2

## @time

In [40]:
insertionsort(xs) = insertionsort!(copy(xs))

function insertionsort!(xs)
    @inbounds for i in 2:length(xs)
        j = i
        while j > 1 && xs[j-1] > xs[j]
            xs[j-1], xs[j] = xs[j], xs[j-1]
            j -= 1
        end
    end
    xs
end

insertionsort([1.0, 0.0])

2-element Array{Float64,1}:
 0.0
 1.0

In [42]:
xs = randn(10000);

In [43]:
#@timeはコードの実行時間とメモリの使用量を返してくれる
GC.gc()
@time insertionsort(xs);

  0.035959 seconds (6 allocations: 78.359 KiB)


# モジュール

In [44]:
#モジュールは"module ~ end"で定義
#名前空間が分けられるので多重ディスパッチであっても他の関数などと衝突しない
module ModFoo #module定義の始まり

struct Foo
    x
end

function show(x)
    print("!! " * string(x) * " !!")
end

end　#moduke定義の終わり

Main.ModFoo

In [45]:
#<モジュール名>.<型/関数名>でアクセス
f = ModFoo.Foo("something")

Main.ModFoo.Foo("something")

In [46]:
ModFoo.show(f)

!! Main.ModFoo.Foo("something") !!

In [47]:
#もともとあるshow関数とは衝突しない
show(f)

Main.ModFoo.Foo("something")

## モジュールの使い方

In [48]:
#module"Geo"を定義
module Geo

export Point, distance, iswithin, move

struct Point
    x::Float64
    y::Float64
    z::Float64
end

distance(a::Point, b::Point) = sqrt(sqdist(a, b))

iswithin(p::Point, c::Point, r::Real) = sqdist(p, c) <= r^2

function move(p::Point, dx, dy, dz)
    return Point(p.x + dx, p.y + dy, p.z + dz)
end

sqdist(a::Point, b::Point) = (a.x - b.x)^2 + (a.y - b.y)^2 + (a.z - b.z)^2

end

Main.Geo

In [49]:
#モジュールで定義された関数などを現在のモジュール(Main)で使いたい場合はusingを用いる
using .Geo

In [50]:
#usingを用いると"Geo."をつけなくてもexportで指定された値や関数を使うことができる
po = Point(0, 0, 0)
p1 = Point(1, 1, 1)

Point(1.0, 1.0, 1.0)

In [51]:
distance(po, p1)

1.7320508075688772

In [52]:
#exportで指定されてないものは使えない
sqdist(po, p1)

UndefVarError: UndefVarError: sqdist not defined

In [53]:
#exportの指定がないものは明示的にモジュールの名前を与えなくてはならない
Geo.sqdist(po, p1)

3.0

## パッケージ

パッケージのインストール。ここでは関数の数値最適化パッケージをインストール

In [54]:
using Pkg
Pkg.update()
Pkg.add("Optim")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %                             ]  25.4 %Fetching: [===========>                             ]  25.7 %                       ]  41.3 %=======================>                 ]  57.1 %Fetching: [=============================>           ]  72.1 %    ]  87.7 % Resolving package versions...
 Installed MbedTLS ─ v0.6.6
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [739be429] ↑ MbedTLS v0.6.4 ⇒ v0.6.6
  Building MbedTLS → `~/.julia/packages/MbedTLS/r1Ufc/deps/build.log`
 Resolving package versions...
 Installed SortingAlgorithms ────── v0.3.1
 Installed NaNMath ──────────────── v0.3.2
 Installed PositiveFactorizations ─ v0.2.1
 Installed DiffResults ──────────── v0.0.3
 Installed SpecialFunctions ─────── v0.7.2
 Installed ForwardDiff

In [55]:
using Optim

┌ Info: Precompiling Optim [429524aa-4258-5aef-a3af-852621145aeb]
└ @ Base loading.jl:1189


In [56]:
#関数の定義
#(1,1)で最小値をとる
func(x, a=1, b=100) = (a - x[1])^2 + b * (x[2] - x[1]^2)^2

func (generic function with 3 methods)

In [57]:
optimize(func,[10.0, 10.0])

Results of Optimization Algorithm
 * Algorithm: Nelder-Mead
 * Starting Point: [10.0,10.0]
 * Minimizer: [1.0000076575345525,1.0000090769441363]
 * Minimum: 3.950131e-09
 * Iterations: 103
 * Convergence: true
   *  √(Σ(yᵢ-ȳ)²)/n < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 198

## 行列の扱い方

In [1]:
a = [1.0, 1.1, 1.2, 1.3]
b = [2.2, 2.4, 2.6, 2.8]
c = [3.9, 3.6, 3.3, 3.1]

m = hcat(a,b,c)

4×3 Array{Float64,2}:
 1.0  2.2  3.9
 1.1  2.4  3.6
 1.2  2.6  3.3
 1.3  2.8  3.1

### 行の削除

In [2]:
#２行目を削除
m[1:size(m,1) .!= 2,: ]

3×3 Array{Float64,2}:
 1.0  2.2  3.9
 1.2  2.6  3.3
 1.3  2.8  3.1

### 列の削除

In [3]:
#２列目を削除
m[:, 1:size(m)[2] .!= 2]

4×2 Array{Float64,2}:
 1.0  3.9
 1.1  3.6
 1.2  3.3
 1.3  3.1