In [1]:
import numpy as np
import copy
from itertoools import chain, combinations

In [2]:
n = 5 # number of agents
phi = 0.2

In [3]:
# initial network
G = np.ones((n,n))
for i in range(n):
    G[i, i] = 0 
G

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [4]:
alpha = np.array([1, 1, 1, 1, 1])

In [5]:
# cost matrix
C = np.array([[0, 6, 0.1, 2, 3],
                         [0.2, 0, 0.5, 0.02, 1],
                         [0.01, 3.5, 0, 2, 0],
                         [2.5, 7, 0.1, 0, 5],
                         [4, 1, 0.12, 3, 0]])

In [6]:
# the set of agents who do not take best response
NB = np.array([i for i in range(n)])

In [7]:
# compute each agents' payoffs
def compute_payoff(G):
    #v = np.array([sum(np.linalg.inv(np.eye(n) - phi * G)[i,:]) for i in range(n)])
    v = np.linalg.inv(np.eye(n) - phi * G) @ alpha
    bool_matrix = G == 1
    cost = np.array([sum(C[i, bool_matrix[i]]) for i in range(n)])
    return v - cost

In [8]:
curr_payoff = compute_payoff(G)

In [9]:
NB = NB[curr_payoff < alpha]

In [10]:
NB

array([0, 2, 3, 4])

In [11]:
a = np.random.choice(NB, 1)

In [12]:
a

array([0])

In [13]:
# take best response
def best_response(player_ind, G):
    player_ind = int(player_ind)
    G_copy = copy.copy(G)
    payoff = compute_payoff(G_copy)[player_ind]
    delete_edge = []
    bool_matrix = G == 1
    
    # current edges
    bool_edge = bool_matrix[player_ind]
    while payoff < alpha[player_ind]:
        max_cost = np.max(C[player_ind, bool_edge])
        edge = int(np.where(C[player_ind,:] == max_cost)[0])
        
        # delete the edge
        G_copy[player_ind, edge] = 0
        
        # compute new payoff
        payoff = compute_payoff(G_copy)[player_ind]
        delete_edge.append(edge)
        bool_edge[edge] = False
        
    return delete_edge

In [14]:
best_response(a, G)

[1, 4, 3]

In [ ]:
def powerset(iterable):
    s = list(iterable)
    if s = []:
        return s
    else:
        return chain.from_iterable(combinations(s,r) for r in range(1, len(s)+1))

In [ ]:
def check_best_response(G):
    NB = {}
    payoff = compute_payoff(G)
    for i in range(n):
        max_payoff = payoff[i]
        remove_edges = []
        edges_index = [i for i, x in enumerate(G[i,:]) if x == 1]
        delte_edges = power_set(edges_index)
        for delete_edge in delete_edges:
            G_copy = copy.copy(G)
            for edge in delete_edge:
                G_copy[i, edge] = 0
            new_payoff = compute_payoff(G_copy)[i]
            if new_payoff > max_payoff:
                max_payoff = new_payoff
                remove_edges = list(delete_edge)
        NB[i] = remove_edges
    
    return NB

In [ ]:
def main(G):
    NB = check_best_response(G)
    NB_agents = [k for k, v in NB.items() if v != []]
    if NB_agents != []:
        agent = np.random.choice(NB_agents, 1)
        remove_edges = NB.values(agent)
        for edge in remove_edges:
            G[agent, edge] = 0
    return G